from setuptools import setup, find_packages

setup(
    name='qmpy',
    version='1.2.0',
    author='S. Kirklin',
    author_email='scott.kirklin@gmail.com',
    license='LICENSE.txt',
    classifiers=["Programming Language :: Python :: 2.7"],
    packages=find_packages(),
    scripts=['bin/oqmd', 'bin/qmpy'],
    url='http://pypi.python.org/pypi/qmpy',
    description='Suite of computational materials science tools',
    include_package_data=True,
    long_description=open('README.md').read(),
    install_requires=[
        "Django == 1.8.18",
        "PuLP == 1.6.10",
        "numpy == 1.16.4",
        "scipy == 0.13.3",
        "MySQL-python == 1.2.5",
        "matplotlib == 2.2.4",
        "networkx < 2.3",
        "pytest",
        "python-memcached == 1.53",
        "ase == 3.11.0",
        "django-extensions < 1.6.8",
        "lxml == 3.6.4",
        "spglib == 1.12.2",
        "PyCifRW >= 4.3",
        "pexpect == 4.2.1",
        "pyparsing == 2.4.2",
        "PyYAML == 3.10",
        "scikit-learn",
        "bokeh == 0.12.15",
        "djangorestframework == 3.6.4",
        "django-crispy-forms",
        "lark-parser ==0.7.1"
    ],
)
